pesquisas/urls.py
from django.conf import settings
from django.urls import path

from pesquisas import views

app_name = 'pesquisas'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('pesquisaHome/', views.pesquisaHome, name='pesquisaHome'),
    path('pesquisaCadastrar/', views.pesquisaCadastrar, name='pesquisaCadastrar'),
    path('pesquisaListar/', views.pesquisaListar, name='pesquisaListar'),
    path('pesquisaGrafico/', views.pesquisaGrafico, name='pesquisaGrafico'),
]

pi3wos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pesquisas.urls', namespace='pesquisas'))
]

pesquisas/models.py
from django.db import models


class Pesquisa(models.Model):
    autores = models.TextField('Autor', null=True, blank=True)
    titulo = models.TextField('Título', null=True, blank=True)
    fonte_artigo = models.TextField('Fonte', null=True, blank=True)
    palavras_chave = models.TextField('Palavra chave', null=True, blank=True)
    resumo_artigo = models.TextField('Resumo', null=True, blank=True)
    endereco_autores = models.TextField('Endereço', null=True, blank=True)
    instituicao_autores = models.TextField('Instituição', null=True, blank=True)
    agencia_fomento = models.TextField('Agência', null=True, blank=True)
    contagem_citacoes = models.PositiveIntegerField('Citação', default=1)
    ano_publicacao = models.CharField ('Publicação', max_length=10, null=True, blank=True)
    areas_pesquisa = models.CharField ('Área pesquisa', max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Pesquisa'
        verbose_name_plural = 'Pesquisas'
        ordering = ['id']
    
    def __str__(self):
        return self.titulo

pesquisas/forms.py
from django import forms

from .models import Pesquisa


class PesquisaForm(forms.ModelForm):
    class Meta:
        model = Pesquisa
        fields = [
            'autores',
            'titulo',
            'fonte_artigo',
            'palavras_chave',
            'resumo_artigo',
            'endereco_autores',
            'instituicao_autores',
            'agencia_fomento',
            'contagem_citacoes',
            'ano_publicacao',
            'areas_pesquisa',
        ]

pesquisas/views.py
import csv
import io

import pandas as pd
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Pesquisa


def save_data(data):
    aux = []
    for item in data:
        autores = item.get('Autores')
        titulo = item.get('Título')
        fonte_artigo = item.get('Fonte do artigo')
        palavras_chave = item.get('Palavras-chave')
        resumo_artigo = item.get('Resumo do artigo')
        endereco_autores = item.get('Endereço dos Autores')
        instituicao_autores = item.get('Instituição de vínculo dos autores')
        agencia_fomento = item.get('Agência de Fomento')
        contagem_citacoes = item.get('Contagem do número de citações')
        ano_publicacao = item.get('Ano da publicação')
        areas_pesquisa = item.get('Áreas de pesquisa')
        obj = Pesquisa(
            autores = autores,
            titulo = titulo,
            fonte_artigo = fonte_artigo,
            palavras_chave = palavras_chave,
            resumo_artigo = resumo_artigo,
            endereco_autores = endereco_autores,
            instituicao_autores = instituicao_autores,
            agencia_fomento = agencia_fomento,
            contagem_citacoes = contagem_citacoes,
            ano_publicacao = ano_publicacao,
            areas_pesquisa = areas_pesquisa,
        )
        aux.append(obj)
    Pesquisa.objects.bulk_create(aux)


def home(request):
    return render(request, 'pesquisas/home.html')


def login(request):
    return render(request, 'pesquisas/login.html')


def pesquisaHome(request):
    return render(request, 'pesquisas/pesquisaHome.html')


def pesquisaCadastrar(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        file = myfile.read().decode('utf-8')
        reader = csv.DictReader(io.StringIO(file))
        data = [line for line in reader]
        save_data(data)
        return HttpResponseRedirect(reverse('pesquisas:pesquisaListar'))
    return render(request, 'pesquisas/pesquisaCadastrar.html')


def pesquisaListar(request):
    pesquisas = Pesquisa.objects.all()
    context = {
        'pesquisas': pesquisas
    }    
    return render(request, 'pesquisas/pesquisaListar.html', context)


def pesquisaGrafico(request):
    pesquisas = Pesquisa.objects.values('instituicao_autores')
    df_counts = pd.DataFrame(pesquisas)
    df_counts = df_counts.value_counts(dropna=False).reset_index()
    df_counts.columns = ['Instituição', 'Citação']    
    df10 = df_counts.iloc[:10]
    dfl = df10.values.tolist()    
    for i in range(len(dfl)):
        for j in range(len(dfl[i])):
            if dfl[i][j] == '':
                dfl[i][j] = 'Instituição não definida'
    return render(request,'pesquisas/pesquisaGrafico.html', {'dflist': dfl})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
    <title>Projeto Integrador PI III</title>
  {% endblock head %}
  <!-- Estilos -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/pages-styles.css' %}">
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  <!-- Font Awesome -->
<script src="https://kit.fontawesome.com/76a4da8fc7.js" crossorigin="anonymous"></script>
</head>
<body>
  <header>
    <div class="container" id="nav-container">
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark">
        <a class="navbar-brand" href="{% url 'pesquisas:home' %}">
          <img id="logo" src="{% static 'img/logopi.png' %}" alt="PI WoS"> PI WoS
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links" aria-controls="navbar-links" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
          <div class="navbar-nav">          
            <a class="nav-item nav-link" id="home-menu" href="#">Home</span></a>
            <a class="nav-item nav-link" id="about-menu" href="#">PI III</a>
            <a class="nav-item nav-link" id="team-menu" href="#">Integrantes</a>
            <a class="nav-item nav-link" id="repository-menu" href="#">Repositório</a>
            <a class="nav-item nav-link" id="contact-menu" href="#">Contato</a>
            <a class="nav-item nav-link" id="contact-menu" href="{% url 'pesquisas:pesquisaHome' %}">Pesquisa Home</a>
            <a class="nav-item nav-link" id="login-menu" href="{% url 'pesquisas:login' %}">Logar</a>
          </div>
        </div>
      </nav>
    </div>
  </header>

{% block content %}

{% endblock content %}

<script src="{% static 'js/navbar-scripts.js' %}"></script>
</body>
</html>

templates/pesquisas/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Projeto Integrador PI III - Home</title>
{% endblock head %}


{% block content %}

  <main>
    <div class="container-fluid">
      <!-- slider -->
      <div id="mainSlider" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#mainSlider" data-slide-to="0" class="active"></li>
          <li data-target="#mainSlider" data-slide-to="1"></li>          
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/banner1.jpg' %}" class="d-block w-100" alt="Univesp PI WOS">
            <div class="carousel-caption d-md-block">
              <h2 class="font-banner1">Projeto Integrador em Computação III</h5>
              <p class="font-banner1">Desenvolvendo uma aplicação web, uso e fornecimento de API, e análises de dados.</p>              
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/banner2.jpg' %}" class="d-block w-100" alt="Engenharia de software">
            <div class="carousel-caption d-md-block">
              <h2 class="font-banner2">Aplicação com framework Django</h5>
              <p class="font-banner2">ETL de pesquisa da plataforma “Web of Science” com Python.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#mainSlider" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#mainSlider" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <!-- Sobre o projeto -->
      <div id="about-area">
        <div class="container">
            <div class="row">
              <div class="col-12"> 
                <h3 class="main-title">Projeto Integrador em Computação III</h3>
              </div>
              <div class="col-md-6">
                <img class="img-fluid" src="{% static 'img/univesp.jpg' %}" alt="Univesp">
              </div>
              <div class="col-md-6">
                <h3 class="about-title">Tema escolhido pelo grupo com base no tema norteador da Univesp</h3>
                <p>Desenvolver um software com framework web ou aplicativo que utilize banco de dados, inclua script web (Javascript), nuvem, acessibilidade, controle de versão, integração contínua e testes. Incluir um dos: uso e fornecimento de API, análises de dados e IoT.</p>
                <p>Objetivos:</p>
                <ul id="about-list">
                  <li><i class="fas fa-check"></i> Realizar análise dos dados da pesquisa da WoS</li>
                  <li><i class="fas fa-check"></i> Utilização framework web Django</li>
                  <li><i class="fas fa-check"></i> Banco de dados PostgreSQL</li>
                  <li><i class="fas fa-check"></i> API com framework Vue.js</li>                  
                  <li><i class="fas fa-check"></i> Layout responsivo para todos os dispositivos</li>
                  <li><i class="fas fa-check"></i> Análise de dados com as bibliotecas Pandas</li>
                  <li><i class="fas fa-check"></i> Criação de gráficos com Google Charts</li>
                  <li><i class="fas fa-check"></i> Desenvolvimento com metodologia ágil</li>
                </ul>
              </div>
            </div>
          </div>
      </div>
      <!-- Integrantes -->
      <div id="team-area">
        <div class="container">
          <div class="row" id="team-photos">
            <div class="col-12">
                <h3 class="main-title">UNICEU-Turma 006 Integrantes</h3>
            </div>            
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilem.jpg' %}" class="card-img-top" alt="Imagem de Perfil 1">
                <div class="card-body">
                  <h5 class="card-title">Afonso Benjamin</h5>
                  <p class="card-text">Desenvolvedor</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilem.jpg' %}" class="card-img-top" alt="Imagem de Perfil 2">
                <div class="card-body">
                  <h5 class="card-title">Fabio Zanin</h5>
                  <p class="card-text">Desenvolvedor</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilem.jpg' %}" class="card-img-top" alt="Imagem de Perfil 3">
                <div class="card-body">
                  <h5 class="card-title">Helio Galdino</h5>
                  <p class="card-text">Desenvolvedor</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row"  id="team-photos">
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilef.jpg' %}" class="card-img-top" alt="Imagem de Perfil 4">
                <div class="card-body">
                  <h5 class="card-title">Elizabeth do Nascimento</h5>
                  <p class="card-text">Gestão e Documentação</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilef.jpg' %}" class="card-img-top" alt="Imagem de Perfil 5">
                  <div class="card-body">
                    <h5 class="card-title">Gessyca Suenaga</h5>
                    <p class="card-text">Gestão e Documentação</p>
                  </div>
                </div>
            </div>
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilem.jpg' %}" class="card-img-top" alt="Imagem de Perfil 6">
                <div class="card-body">
                  <h5 class="card-title">Gilberto Damacena</h5>
                  <p class="card-text">Gestão e Documentação</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row" id="team-photos">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
              <div class="card">
                <img src="{% static 'img/profilem.jpg' %}" class="card-img-top" alt="Imagem de Perfil 7">
                <div class="card-body">
                  <h5 class="card-title">Ricardo Oliveira</h5>
                  <p class="card-text">ETL de dados</p>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
  <!-- Repositorio -->
	<div id="repository-area">
        <div class="container">
          <div class="row">
            <div class="col-12">
                <h3 class="main-title">Reposiório GitHub e vídeo YouTube</h3>
			</div>
    			<div class="col-md-6">
				  <div class="card">
					<img src="{% static 'img/githublogo.png' %}" id="repository-area-img" alt="GitHub">
					<div class="card-body">
					  <h5 class="card-title">Repositorio GitHub</h5>
					  <p class="card-text">Link</p>
					</div>
				  </div>
				</div>
				<div class="col-md-6">
				  <div class="card">
					<img src="{% static 'img/youtubelogo.jpg' %}" id="repository-area-img" alt="Youtube">
					<div class="card-body">
					  <h5 class="card-title">Video no Youtube</h5>
					  <p class="card-text">Link</p>
					</div>
				  </div>
				</div>
          </div>
        </div>
      </div>
      
    </div>
  </main>
    <!-- Rodapé -->
  <footer>
    <div id="contact-area">
      <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h3 class="main-title">Entre em contato conosco</h3>
            </div>
            <div class="col-md-12 contact-box">
              <i class="fas fa-envelope"></i>
              <p><span class="contact-tile">Envie um email:</span> contato@email.com.br</p>
            </div>
          </div>
      </div>
    </div>
      <!-- Copy -->
    <div id="copy-area">
      <div class="container">
        <div class="row">
            <div class="col-md-12">
              <p>Desenvolvido por UNICEU-PI III-Turma 006 &copy; 2022</p>
            </div>
        </div>
      </div>
    </div>
  </footer>

  {% endblock content %}

templates/pesquisas/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PI WoS Login</title>  
  <link rel="stylesheet" href="{% static 'css/login-styles.css' %}">
</head>
<body background="{% static 'img/webofsciencelogin.jpg' %}">
  <div id="login-container">
    <h1>Login</h1>
    <form action="">
      <label for="email">E-mail</label>
      <input type="email" name="email" id="email" placeholder="Digite seu e-email" autocomplete="off" autofocus>
      <label for="password">Senha</label>
      <input type="password" name="password" id="password" placeholder="Digite sua senha">
      <a href="#" id="forgot-pass">Esqueceu a senha?</a>
      <input type="submit" value="Login">
    </form>
    <div id="register-container">
      <p>Ainda não tem uma conta?</p>
      <a href="#">Registrar</a>
      <a href="{% url 'pesquisas:home' %}">Home</a>      
    </div>
  </div>
</body>
</html>

templates/pesquisas/pesquisaCadastrar.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Projeto Integrador PI III - Pesquisas</title>
{% endblock head %}


{% block content %}
<main>
    <div id="content-area">
      <div class="container">
          <div class="row">
            <div class="col-12"> 
              <h3 class="title-pesquisa">Carregar Pesquisas</h3>
            </div>

            <div class="col-md-12 title-pesquisa">
                <div>
                    <h1>Carregar arquivo CSV</h1>        
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input name="myfile" type="file" />
                        <button type="submit" class="btn btn-success">Upload</button>
                      </form>
                </div>
            </div>

          </div>
        </div>
    </div>

  </div>
</main>
{% endblock content %}

templates/pesquisas/pesquisaGrafico.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['bar']});
  google.charts.setOnLoadCallback(drawStuff);

  function drawStuff() {
    var data = new google.visualization.arrayToDataTable([
      ['Instituição', 'Citação'],
      {% for i in dflist %}
        ['{{i.0}}', {{i.1}}],
      {% endfor %}
      ]);
      

    var options = {
      title: 'Chess opening moves',
      width: 900,
      legend: { position: 'none' },
      // chart: { title: 'Resultado das dez instituições com maiores ocorrências de publicações.'},
      bars: 'horizontal', // Required for Material Bar Charts.
      axes: {
        x: {
          0: { side: 'top', label: 'Citação'} // Top x-axis.
        }
      },
      bar: { groupWidth: "90%" }
    };

    var chart = new google.charts.Bar(document.getElementById('top_x_div'));
    chart.draw(data, options);
  };
</script>
  <title>Projeto Integrador PI III - Pesquisas Gráfico</title>
{% endblock head %}


{% block content %}
<main>
    <div id="content-area">
      <div class="container">
          
          <div class="row">           
            <div class="col-12"> 
              <h3 class="title-pesquisa">Resultado das dez instituições com maiores ocorrências de publicações.</h3>
            </div>

          </div>

          <div class="row">
            <div class="col-12" id="top_x_div" style="width: 900px; height: 400px;"></div>
          </div>
          
          <div class="row">           
            <div class="col-md-12">
            <h3 class="title-pesquisa">Tabelas das 10 citações mais repetidas.</h3>
            </div>
          </div>          
          
          <div class="row" id="tabela-pesquisa">
            <div class="col-6">
              <table id="listar-pesquisa" class="table table-sm table-striped table-hover table-bordered acessibilidade">
                <thead class="thead-dark">
                  <tr>
                    <th class="text-center" scope="col"><b>Instituição</b></th>
                    <th class="text-center" scope="col"><b>Citação</b></th>
                  </tr>
                </thead>
                <tbody>
                  {% for l in dflist %}
                    <tr>          
                      <td class="text-justify">{{ l.0 }}</td>
                      <td class="text-justify">{{ l.1 }}</td>
                    </tr>
                  {% endfor %}  
                </tbody>
              </table>
            </div>
          </div>

        </div>
    </div>

</main>
{% endblock content %}

templates/pesquisas/pesquisaHome.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Projeto Integrador PI III - Pesquisas</title>
{% endblock head %}


{% block content %}
<main>
    <div id="content-area">
      <div class="container">
          <div class="row">
            <div class="col-12"> 
              <h3 class="title-pesquisa">Pesquisas</h3>
            </div>
            <div class="col-md-12">
                <p><a href="{% url 'pesquisas:pesquisaCadastrar' %}">pesquisaCadastrar</a></p>
                <p><a href="{% url 'pesquisas:pesquisaListar' %}">pesquisaListar</a></p>
                <p><a href="{% url 'pesquisas:pesquisaGrafico' %}">pesquisaGrafico</a></p>
            </div>
          </div>
        </div>
    </div>

  </div>
</main>
{% endblock content %}

templates/pesquisas/pesquisaListar.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Projeto Integrador PI III - Pesquisas</title>
{% endblock head %}


{% block content %}
<main>
    <div id="content-area">
      <div class="container">
          <div class="row">

            <div class="col-12"> 
              <h3 class="title-pesquisa">Pesquisas</h3>
            </div>
            
            <div class="col-sm m-auto pt-2 pb-2 acessibilidade" text-center>
                <table id="listar-pesquisa" class="table table-sm table-striped table-hover table-bordered acessibilidade">
                  <thead class="thead-dark">
                    <tr>
                      <th class="text-center" scope="col">Autores</th>
                      <th class="text-center" scope="col">Título</th>
                      <th class="text-center" scope="col">Fonte do artigo</th>
                      <th class="text-center" scope="col">Palavras-chave</th>
                      <!--<th class="text-center" scope="col">Resumo do artigo</th>-->
                      <th class="text-center" scope="col">Endereço dos Autores</th>
                      <th class="text-center" scope="col">Instituição de vínculo dos autores</th>
                      <th class="text-center" scope="col">Agência de Fomento</th>
                      <th class="text-center" scope="col">Número de citações</th>
                      <th class="text-center" scope="col">Ano da publicação</th>
                      <th class="text-center" scope="col">Áreas de pesquisa</th>
                      <th class="text-center" scope="col">Ações</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for pesquisa in pesquisas %}
                      <tr>
                        <td class="text-justify">{{ pesquisa.autores }}</td>
                        <td class="text-justify">{{ pesquisa.titulo }}</td>
                        <td class="text-justify">{{ pesquisa.fonte_artigo }}</td>
                        <td class="text-justify">{{ pesquisa.palavras_chave }}</td>
                        <!--<td class="text-justify">{{ pesquisa.resumo_artigo }}</td>-->
                        <td class="text-justify">{{ pesquisa.endereco_autores }}</td>
                        <td class="text-justify">{{ pesquisa.instituicao_vinculo_autores }}</td>
                        <td class="text-justify">{{ pesquisa.agencia_fomento }}</td>
                        <td class="text-justify">{{ pesquisa.contagem_citacoes }}</td>
                        <td class="text-justify">{{ pesquisa.ano_publicacao }}</td>
                        <td class="text-justify">{{ pesquisa.areas_pesquisa }}</td>
                        <td class="text-justify">
                          <a href="" ><i class="fa-solid fa-pen"></i></a>
                          <a href="" ><i class="fa-solid fa-trash"></i></a>
                        </td>
                      </tr>
                    {% endfor %}  
                  </tbody>
                </table>
              </div>
              
          </div>
        </div>
    </div>

  </div>
</main>
{% endblock content %}